name: coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: game-testing-coverage
          path: .
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tilt-us/mira-game-files
          files: ./coverage.lcov
